name: JavaGoat-WhatsApp-Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5   # v4

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020    # v4 (replace with actual)
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Start AI Bot
        env:
          FIREBASE_URL: ${{ secrets.FIREBASE_URL }}
        run: npm start
